# Generated by Django 4.0.2 on 2023-03-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shoe_name', models.CharField(max_length=100)),
                ('Shoe_image', models.ImageField(upload_to='')),
                ('Shoe_price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shoe',
            },
        ),
    ]
